package Classe;
// Generated 20 janv. 2018 13:04:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int id;
     private String cni;
     private String telp;
     private String nom;
     private String prenom;
     private Date datenaissance;
     private String quartier;

    public Client() {
    }

	
    public Client(int id, String cni, String telp, String nom) {
        this.id = id;
        this.cni = cni;
        this.telp = telp;
        this.nom = nom;
    }
    public Client(int id, String cni, String telp, String nom, String prenom, Date datenaissance, String quartier) {
       this.id = id;
       this.cni = cni;
       this.telp = telp;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.quartier = quartier;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCni() {
        return this.cni;
    }
    
    public void setCni(String cni) {
        this.cni = cni;
    }
    public String getTelp() {
        return this.telp;
    }
    
    public void setTelp(String telp) {
        this.telp = telp;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
    public String getQuartier() {
        return this.quartier;
    }
    
    public void setQuartier(String quartier) {
        this.quartier = quartier;
    }




}


