package Classe;
// Generated 14 janv. 2018 09:08:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Operateur generated by hbm2java
 */
public class Operateur  implements java.io.Serializable {


     private int id;
     private String designation;
     private Set informationses = new HashSet(0);

    public Operateur() {
    }

	
    public Operateur(int id, String designation) {
        this.id = id;
        this.designation = designation;
    }
    public Operateur(int id, String designation, Set informationses) {
       this.id = id;
       this.designation = designation;
       this.informationses = informationses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public Set getInformationses() {
        return this.informationses;
    }
    
    public void setInformationses(Set informationses) {
        this.informationses = informationses;
    }




}


