package Classe;
// Generated 14 janv. 2018 09:08:16 by Hibernate Tools 4.3.1



/**
 * Tabdroit generated by hbm2java
 */
public class Tabdroit  implements java.io.Serializable {


     private int id;
     private String designation;

    public Tabdroit() {
    }

    public Tabdroit(int id, String designation) {
       this.id = id;
       this.designation = designation;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }




}


